---
include:
  - project: "Bigouden/gitlab-ci-templates"
    file: ".gitlab-ci-docker.yml"
  - project: "Bigouden/gitlab-ci-templates"
    file: ".gitlab-ci-owasp-zap.yml"

.services:
  services:
    - name: $CONTAINER_TEST_IMAGE
      alias: exporter
  image: $CONTAINER_CLIENT_IMAGE
  before_script:
    - apk add --no-cache --update curl
  variables:
    GIT_STRATEGY: none
    DOCKER_HOST: $DOCKER_HOST
  dependencies: []

variables:
  PROMETHEUS_EXPORTER_PORT: "8123"
  DOCKER_DISK_USAGE_EXPORTER_SCHEME: "http"
  CI_DEBUG_SERVICES: "true"
  OWASP_ZAP_TARGET: ${DOCKER_DISK_USAGE_EXPORTER_SCHEME}://target:${PROMETHEUS_EXPORTER_PORT}

stages:
  - Quality
  - Security
  - Build
  - Test
  - Inspect
  - Release
  - Clean

Prometheus Exporter:
  stage: Test
  extends: .services
  script:
    - curl -f --connect-timeout 60 ${DOCKER_DISK_USAGE_EXPORTER_SCHEME}://exporter:${PROMETHEUS_EXPORTER_PORT}/metrics
